name: vndb_lite
description: "A lite open-source mobile version of your favorite vndb.org website."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.1+1
environment:
  sdk: ">=3.4.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # Splash screen customization.
  flutter_native_splash: ^2.4.1

  # App theme font customization.
  google_fonts: ^6.2.1

  # Easy to use package name changer.
  change_app_package_name: ^1.3.0

  # Powerful state management solution.
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Collection of flag widgets from language or country codes
  flag: ^7.0.0

  # Easy and efficient way to check internet connection.
  internet_connection_checker_plus: ^2.5.0

  # Hides bottom navigation bar when scrolling downward, shows when upward.
  scroll_to_hide: ^2.1.0

  # Native share link functionality.
  share_plus: ^10.0.0

  # Native url launcher functionality.
  url_launcher: ^6.3.0

  # Local database/storage utility.
  shared_preferences: ^2.2.3

  # Better version of network image.
  cached_network_image: ^3.3.1

  # Easy to use to hide/unhide long paragraphs.
  readmore: ^3.0.0

  # A better version of tab bar view.
  contentsize_tabbarview: ^0.0.2

  # Swipes widget screenshots.
  card_swiper: ^3.0.1

  # Datetime utility.
  intl: ^0.20.0

  # Unique id generator.
  uuid: ^4.4.2

  # Handle network requests.
  dio: ^5.5.0+1

  # Native notification.
  flutter_local_notifications: ^18.0.1

  # Prevent user to close the app when tapping back button.
  double_back_to_close_app: ^2.1.0

  # Shows vndb stats chart.
  fl_chart: ^0.70.2

  # Overlay selection.
  gradient_borders: ^1.0.1

  # App icon customization.
  flutter_launcher_icons: ^0.14.1

  # Vote selection dropdown button.
  dropdown_button2: ^2.3.9

  # Handle app cache.
  flutter_cache_manager: ^3.4.1

  # Synthetic recycleview.
  visibility_detector: ^0.4.0+2

  # Refresh screen.
  pull_to_refresh: ^2.0.0

  # App information provider.
  package_info_plus: ^8.1.0

  # Network logging.
  pretty_dio_logger: ^1.4.0

  # App routing.
  go_router: ^14.6.1

  # Better colletion data api.
  collection: ^1.18.0

  # Handles version check.
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0

  # Helps code faster and lesser.
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/images/bg/
    - assets/images/status/
    - assets/images/contact/
    - assets/images/icon/
    - assets/images/os_image/
    - assets/images/splash/
    - assets/images/status/
    - assets/images/tutorial/
