name: vndb_lite
description: "A lite, free, and open-source mobile version of your favorite website, vndb.org."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

#
# ======================================================================================================
#

version: 3.5.2+1

#
# ======================================================================================================
#

environment:
  sdk: ^3.7.2

#
# ======================================================================================================
#

dependencies:
  flutter:
    sdk: flutter

  # Logging
  logger: ^2.5.0

  # App information provider.
  package_info_plus: ^8.1.0

  # Handles version check.
  version: ^3.0.2

  # Unique id generator.
  uuid: ^4.5.1

  # Splash screen customization.
  flutter_native_splash: ^2.4.1

  # App icon customization.
  # flutter_launcher_icons: ^0.14.1

  # Easy to use package name changer.
  # change_app_package_name: ^1.3.0

  # Easy app renaming.
  # rename_app: ^1.6.2

  # Time utility.
  intl: ^0.20.2

  # Native notification.
  flutter_local_notifications: ^19.1.0

  # Local database/storage utility.
  shared_preferences: ^2.2.3
  # hive_ce: ^2.10.1
  # hive_ce_flutter: ^2.2.0

  # Handy collection library
  collection: ^1.19.0

  # Powerful state management solution.
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # App routing.
  go_router: ^16.0.0
  go_transitions: ^0.8.0

  # Native share link functionality.
  share_plus: ^11.0.0

  # Native url launcher functionality.
  url_launcher: ^6.3.0

  # Handle network requests.
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0

  # Easy and efficient way to check internet connection.
  internet_connection_checker_plus: ^2.5.0

  # Handle caches.
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  # Prevent user to close the app when tapping back button.
  double_back_to_close_app: ^2.1.0

  # Gridview vn widgets
  visibility_detector: ^0.4.0+2
  flutter_staggered_grid_view: ^0.7.0

  # Icons & Decorations
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  gradient_borders: ^1.0.1
  dropdown_button2: ^2.3.9
  fl_chart: ^1.0.0
  card_swiper: ^3.0.1
  animated_text_kit: ^4.2.3

  # Hides bottom navigation bar when scrolling downward, shows when upward.
  # scroll_to_hide: ^2.1.0

  # Easy to use to hide/unhide long paragraphs.
  readmore: ^3.0.0

  # A better version of tabBar view.
  contentsize_tabbarview: ^0.0.2

#
# ======================================================================================================
#

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  # Cool & useful codegen
  build_runner: ^2.4.13

  # Lints
  flutter_lints: ^6.0.0
  custom_lint: ^0.7.0

  # Helps code faster and lesser.
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

  # TODO migrate to HIVE
  # For hive noSQL db.
  # hive_ce_generator: ^1.8.1

  # For testing.
  mocktail: ^1.0.4
  test: ^1.25.8

#
# ======================================================================================================
#

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/bg/
    - assets/images/status/
    - assets/images/contact/
    - assets/images/icon/
    - assets/images/os/
    - assets/images/flags/
    - assets/images/search/
    - assets/images/splash/
    - assets/images/status/
    - assets/images/tutorial/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-RegularBold.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
